#!/bin/sh
# Regenerates Slots.cs (the slot of every member of the interface tables;
# also bridge/managed/Host/Slots.cs, the same for Rexx.Net),
# the member lists (*.txt) and layout.cpp, from oorexxapi.h. Every member is one pointer-sized slot
# (layout.cpp checks it): slot i is at offset i * sizeof(void *).
H=${1:-${REXX_INCLUDE:-/usr/local/include}/oorexxapi.h}   # (sed and awk: POSIX, for macOS too)
# The exit context (exits, command handlers) and the I/O redirector (ADDRESS ...
# WITH) are tables of the same kind, used by the bridge's phase B.
TABLES="RexxInstanceInterface RexxThreadInterface ExitContextInterface IORedirectorInterface"
cd "$(dirname "$0")"
for t in $TABLES; do
  awk -v t="$t" '
    /typedef struct/ { buf = ""; on = 1; next }
    on { buf = buf "\n" $0 }
    on && $0 ~ "} *" t ";" { print buf; exit }' "$H" |
  sed 's://.*$::' |
  sed -n -e 's/.*( *RexxEntry *\* *\([A-Za-z0-9_]*\) *).*/\1/p' \
         -e '/RexxEntry/!s/^[[:space:]]*[A-Za-z_][A-Za-z0-9_[:space:]*]*[[:space:]*]\([A-Za-z_][A-Za-z0-9_]*\)[[:space:]]*;.*/\1/p' > $t.txt
done
{
  echo "// Generated by gen-slots.sh from oorexxapi.h: do not edit."
  echo "namespace HostApi;"
  for t in $TABLES; do
    echo "static class ${t#Rexx}"
    echo "{"
    awk '{ printf "    public const int %s = %d;\n", $1, NR - 1 }' $t.txt
    echo "}"
  done
} > Slots.cs
{
  echo "// layout: prints the offset of every member of the four interface tables."
  echo "// Generated by gen-slots.sh from oorexxapi.h: do not edit. run.sh checks"
  echo "// that member i sits at offset i * 8 (one pointer-sized slot each)."
  echo "#include <oorexxapi.h>"
  echo "#include <stdio.h>"
  echo "#include <stddef.h>"
  echo "int main() {"
  for t in $TABLES; do
    printf '  printf("%s %%zu\\n", sizeof(%s));\n' "$t" "$t"
    while read f; do printf '  printf("%s.%s %%zu\\n", offsetof(%s, %s));\n' "$t" "$f" "$t" "$f"; done < $t.txt
  done
  echo "  return 0; }"
} > layout.cpp
# The same slots for the bridge's assembly (Rexx.Net, internal).
mkdir -p ../../bridge/managed/Host
sed -e 's/^namespace HostApi;/namespace Rexx.Net;/' -e 's/^static class/internal static class/' \
    -e 's|^// Generated by gen-slots.sh from oorexxapi.h: do not edit.|// Generated by smoke/hostapi/gen-slots.sh from oorexxapi.h: do not edit.|' \
    Slots.cs > ../../bridge/managed/Host/Slots.cs
