// hostapi: .NET -> ooRexx through the object API, with no native shim
// (08/10/2026). C# reads the interface tables of
// RexxInstance and RexxThreadContext (oorexxapi.h) and calls their entries
// through function pointers: every member of both tables is one pointer-sized
// slot (layout.cpp checks it; Slots.cs is generated by gen-slots.sh).
//
// Probes, each printing "ok <what>" or "FAIL <what>":
//   create        RexxCreateInterpreter from C#, the interpreter's version
//   routine       a routine from source (NewRoutine), called with arguments
//   objects       objects kept by .NET (global references), messages to them
//   package       a package from source, its class, ~new and methods
//   syntax        a Rexx error as a condition, decoded (code, message, line)
//   threads       other .NET threads attach, send, detach (4 at once)
//   command       ADDRESS DOTNET handled by a C# function
//   halt          Halt() from .NET stops a looping Rexx thread
//   bothways      Rexx code of this host using .net (net.cls) in this process
// and two timings (a message on an attached thread; attach + message + detach).
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace HostApi;

public static class Shared { public static string Marker = "default"; }   // for "bothways"

[StructLayout(LayoutKind.Sequential)]
struct RexxCondition
{
    public nint code, rc; public nuint position;
    public nint conditionName, message, errortext, program, description, additional;
}

public sealed class RexxException : Exception
{
    public long Code; public long Line;
    public RexxException(long code, long line, string message) : base(message) { Code = code; Line = line; }
}

static unsafe class Native
{
    [DllImport("rexx")] public static extern int RexxCreateInterpreter(out nint instance, out nint context, nint options);
}

/// A thread context: { RexxInstance *instance; RexxThreadInterface *functions; }.
unsafe readonly struct TC
{
    public readonly nint P;
    public TC(nint p) { P = p; }
    nint F(int slot) => ((nint*)((nint*)P)[1])[slot];

    public void Detach() => ((delegate* unmanaged<nint, void>)F(ThreadInterface.DetachThread))(P);
    public nint Global(nint o) => ((delegate* unmanaged<nint, nint, nint>)F(ThreadInterface.RequestGlobalReference))(P, o);
    public void ReleaseGlobal(nint o) => ((delegate* unmanaged<nint, nint, void>)F(ThreadInterface.ReleaseGlobalReference))(P, o);
    public void ReleaseLocal(nint o) => ((delegate* unmanaged<nint, nint, void>)F(ThreadInterface.ReleaseLocalReference))(P, o);
    public nint Nil => F(ThreadInterface.RexxNil);

    public nint Str(string s)
    {
        var b = Encoding.UTF8.GetBytes(s);
        fixed (byte* p = b) return ((delegate* unmanaged<nint, byte*, nuint, nint>)F(ThreadInterface.NewString))(P, p, (nuint)b.Length);
    }

    public string ToStr(nint o)
    {
        if (o == 0) return "<void>";
        nint s = ((delegate* unmanaged<nint, nint, nint>)F(ThreadInterface.ObjectToString))(P, o);
        var len = ((delegate* unmanaged<nint, nint, nuint>)F(ThreadInterface.StringLength))(P, s);
        var data = ((delegate* unmanaged<nint, nint, byte*>)F(ThreadInterface.StringData))(P, s);
        return Encoding.UTF8.GetString(data, (int)len);
    }

    public nint Array(params string[] items)
    {
        nint a = ((delegate* unmanaged<nint, nuint, nint>)F(ThreadInterface.NewArray))(P, (nuint)items.Length);
        foreach (var i in items) ((delegate* unmanaged<nint, nint, nint, nuint>)F(ThreadInterface.ArrayAppend))(P, a, Str(i));
        return a;
    }

    public nint Send(nint o, string msg, params string[] args)
    {
        var name = Encoding.ASCII.GetBytes(msg.ToUpperInvariant() + "\0");
        nint r;
        fixed (byte* n = name) r = ((delegate* unmanaged<nint, nint, byte*, nint, nint>)F(ThreadInterface.SendMessage))(P, o, n, Array(args));
        Check();
        return r;
    }

    public nint NewRoutine(string name, string source)
    {
        var n = Encoding.UTF8.GetBytes(name + "\0"); var s = Encoding.UTF8.GetBytes(source);
        nint r;
        fixed (byte* pn = n) fixed (byte* ps = s)
            r = ((delegate* unmanaged<nint, byte*, byte*, nuint, nint>)F(ThreadInterface.NewRoutine))(P, pn, ps, (nuint)s.Length);
        Check();
        return r;
    }

    public nint Call(nint routine, params string[] args)
    {
        nint r = ((delegate* unmanaged<nint, nint, nint, nint>)F(ThreadInterface.CallRoutine))(P, routine, Array(args));
        Check();
        return r;
    }

    public nint LoadPackage(string name, string source)
    {
        var n = Encoding.UTF8.GetBytes(name + "\0"); var s = Encoding.UTF8.GetBytes(source);
        nint r;
        fixed (byte* pn = n) fixed (byte* ps = s)
            r = ((delegate* unmanaged<nint, byte*, byte*, nuint, nint>)F(ThreadInterface.LoadPackageFromData))(P, pn, ps, (nuint)s.Length);
        Check();
        return r;
    }

    public nint FindPackageClass(nint package, string name)
    {
        var n = Encoding.ASCII.GetBytes(name + "\0");
        fixed (byte* pn = n) return ((delegate* unmanaged<nint, nint, byte*, nint>)F(ThreadInterface.FindPackageClass))(P, package, pn);
    }

    // A pending condition becomes a RexxException.
    public void Check()
    {
        if (((delegate* unmanaged<nint, nuint>)F(ThreadInterface.CheckCondition))(P) == 0) return;
        nint info = ((delegate* unmanaged<nint, nint>)F(ThreadInterface.GetConditionInfo))(P);
        RexxCondition c;
        ((delegate* unmanaged<nint, nint, RexxCondition*, void>)F(ThreadInterface.DecodeConditionInfo))(P, info, &c);
        string text = c.message != 0 ? ToStr(c.message) : c.errortext != 0 ? ToStr(c.errortext) : ToStr(c.conditionName);
        ((delegate* unmanaged<nint, void>)F(ThreadInterface.ClearCondition))(P);
        throw new RexxException(c.code, (long)c.position, text);
    }
}

/// An instance: { RexxInstanceInterface *functions; void *applicationData; }.
unsafe readonly struct Instance
{
    public readonly nint P;
    public Instance(nint p) { P = p; }
    nint F(int slot) => ((nint*)((nint*)P)[0])[slot];

    public TC Attach()
    {
        nint tc;
        if (((delegate* unmanaged<nint, nint*, nuint>)F(InstanceInterface.AttachThread))(P, &tc) == 0)
            throw new InvalidOperationException("AttachThread failed");
        return new TC(tc);
    }
    public long Version => (long)((delegate* unmanaged<nint, nuint>)F(InstanceInterface.InterpreterVersion))(P);
    public void Halt() => ((delegate* unmanaged<nint, void>)F(InstanceInterface.Halt))(P);
    public void Terminate() => ((delegate* unmanaged<nint, void>)F(InstanceInterface.Terminate))(P);
    public void AddCommandEnvironment(string name, nint handler)
    {
        var n = Encoding.ASCII.GetBytes(name + "\0");
        fixed (byte* pn = n) ((delegate* unmanaged<nint, byte*, nint, int, void>)F(InstanceInterface.AddCommandEnvironment))(P, pn, handler, 1);
    }
}

static unsafe class Program
{
    static int failures;
    static void Ok(bool good, string what, string detail = "")
    {
        Console.WriteLine((good ? "ok   " : "FAIL ") + what + (detail.Length > 0 ? ": " + detail : ""));
        if (!good) failures++;
    }

    static string lastCommand = "";

    // ADDRESS DOTNET 'command': (RexxExitContext *, address, command) -> rc.
    // An exit context starts with its RexxThreadContext *.
    [UnmanagedCallersOnly]
    static nint Command(nint exitContext, nint address, nint command)
    {
        var tc = new TC(*(nint*)exitContext);
        lastCommand = tc.ToStr(address) + ": " + tc.ToStr(command);
        return tc.Str(lastCommand.Length.ToString());
    }

    static int Main()
    {
        // create
        int rc = Native.RexxCreateInterpreter(out nint ip, out nint tp, 0);
        var inst = new Instance(ip); var tc = new TC(tp);
        Ok(rc != 0 && ip != 0, "create", $"interpreter version {inst.Version:x}");

        // routine
        nint routine = tc.Global(tc.NewRoutine("fromdotnet", "use arg a, b; return a + b 'from' .context~package~name"));
        Ok(tc.ToStr(tc.Call(routine, "2", "40")) == "42 from fromdotnet", "routine", tc.ToStr(tc.Call(routine, "2", "40")));

        // objects
        nint arr = tc.Call(tc.NewRoutine("mk", "return .array~of('a', 'b', 'c')"));
        nint kept = tc.Global(arr); tc.ReleaseLocal(arr);
        tc.Send(kept, "append", "d");
        Ok(tc.ToStr(tc.Send(kept, "items")) == "4" && tc.ToStr(tc.Send(kept, "makeString", "line", "-")) == "a-b-c-d",
           "objects", tc.ToStr(tc.Send(kept, "makeString", "line", "-")));

        // package
        nint pkg = tc.LoadPackage("account.cls",
            "::class Account public\n" +
            "::attribute balance get\n" +
            "::method init; expose balance; use arg balance = 0\n" +
            "::method deposit; expose balance; use arg n; balance += n; return balance\n" +
            "::method withdraw; expose balance; use arg n\n" +
            "  if n > balance then raise syntax 88.900 array('insufficient funds:' balance)\n" +
            "  balance -= n; return balance\n");
        nint account = tc.Global(tc.Send(tc.FindPackageClass(pkg, "ACCOUNT"), "new", "100"));
        tc.Send(account, "deposit", "50");
        Ok(tc.ToStr(tc.Send(account, "balance")) == "150", "package", "Account~new(100)~deposit(50)~balance = " + tc.ToStr(tc.Send(account, "balance")));

        // syntax
        try { tc.Send(account, "withdraw", "1000"); Ok(false, "syntax", "no exception"); }
        catch (RexxException e) { Ok(e.Code == 88900 && e.Message.Contains("insufficient funds: 150") && e.Line == 6, "syntax", $"{e.Code} line {e.Line}: {e.Message}"); }
        try { tc.NewRoutine("bad", "say 1 +"); Ok(false, "syntax (compile)", "no exception"); }
        catch (RexxException e) { Ok(e.Code / 1000 == 35, "syntax (compile)", $"{e.Code}: {e.Message}"); }

        // threads: 4 .NET threads, each attaching per call, depositing 1 a thousand times
        var sw = Stopwatch.StartNew();
        Parallel.For(0, 4, new ParallelOptions { MaxDegreeOfParallelism = 4 }, _ =>
        {
            for (int i = 0; i < 1000; i++)
            {
                var t = inst.Attach();
                try { t.Send(account, "deposit", "1"); } finally { t.Detach(); }
            }
        });
        Ok(tc.ToStr(tc.Send(account, "balance")) == "4150", "threads", $"4 x 1000 deposits from attached .NET threads, balance {tc.ToStr(tc.Send(account, "balance"))}, {sw.Elapsed.TotalMilliseconds / 4000 * 1000:F1} µs each");

        // command
        inst.AddCommandEnvironment("DOTNET", (nint)(delegate* unmanaged<nint, nint, nint, nint>)&Command);
        string r = tc.ToStr(tc.Call(tc.NewRoutine("cmd", "address dotnet 'open the door'; return rc")));
        Ok(lastCommand == "DOTNET: open the door" && r == "21", "command", $"handler got \"{lastCommand}\", rc {r}");

        // halt
        nint loop = tc.Global(tc.NewRoutine("loop", "do i = 1; nop; end"));
        string halted = "not halted";
        var th = new Thread(() =>
        {
            var t = inst.Attach();
            try { t.Call(loop); } catch (RexxException e) { halted = $"{e.Code}: {e.Message}"; } finally { t.Detach(); }
        });
        th.Start(); Thread.Sleep(300); inst.Halt();
        Ok(th.Join(5000) && halted != "not halted", "halt", halted);

        // bothways: Rexx code of this host uses .net; is it this runtime and our assemblies?
        Shared.Marker = "set by the host";
        string bridge = Environment.GetEnvironmentVariable("REXXNET_DIR") ?? "/home/claude/build/rexxnet";
        string self = typeof(Shared).Assembly.Location;
        try
        {
            string got = tc.ToStr(tc.Call(tc.NewRoutine("both",
                "use arg self\n" +
                "max = .net~System~Math~Max(3, 7)\n" +
                ".net~load(self)\n" +
                "marker = .net~type('HostApi.Shared')~Marker\n" +
                "alc = ''\n" +
                "all = .net~System~AppDomain~CurrentDomain~GetAssemblies   -- (DO OVER, [i]: phase 2)\n" +
                "do i = 0 to all~Length - 1\n" +
                "  a = all~GetValue(i)\n" +
                "  if a~GetName~Name == 'Rexx.Net' then\n" +
                "    alc = alc .net~System~Runtime~Loader~AssemblyLoadContext~GetLoadContext(a)~ToString\n" +
                "end\n" +
                "pid = .net~System~Environment~ProcessId\n" +
                "return max '|' marker '|' alc '|' pid\n" +
                $"::requires '{bridge}/net.cls'\n"), self));
            var parts = got.Split(" | ");
            Console.WriteLine("     bothways: " + got + "   (host pid " + Environment.ProcessId + ")");
            Ok(parts[0] == "7" && parts[3] == Environment.ProcessId.ToString(), "bothways: .net works in a .NET host");
            Ok(parts[1] == "set by the host", "bothways: the host's own types and statics", "Marker = " + parts[1] + ", Rexx.Net in:" + parts[2]);
        }
        catch (RexxException e) { Ok(false, "bothways", $"{e.Code}: {e.Message}"); }
        // the host references Rexx.Net too: one copy, one handle table
        int before = Rexx.Net.Handles.Count;
        nint keep = tc.Global(tc.Call(tc.NewRoutine("keep", "return .net~System~Text~StringBuilder~new('x')\n" +
                                                            $"::requires '{bridge}/net.cls'\n")));
        int copies = AppDomain.CurrentDomain.GetAssemblies().Count(a => a.GetName().Name == "Rexx.Net");
        // (more than one handle: the object, and its type's from the namespace walk)
        Ok(copies == 1 && Rexx.Net.Handles.Count > before, "bothways: one Rexx.Net, one handle table",
           $"{copies} copy, handles {before} -> {Rexx.Net.Handles.Count} as Rexx made a StringBuilder");
        tc.ReleaseGlobal(keep);

        // timings
        const int N = 100_000;
        sw.Restart();
        for (int i = 0; i < N; i++) tc.Send(kept, "items");
        double attached = sw.Elapsed.TotalMilliseconds / N * 1000;
        double perCall = 0;
        var tt = new Thread(() =>
        {
            var s = Stopwatch.StartNew();
            for (int i = 0; i < N; i++) { var t = inst.Attach(); t.Send(kept, "items"); t.Detach(); }
            perCall = s.Elapsed.TotalMilliseconds / N * 1000;
        });
        tt.Start(); tt.Join();
        Console.WriteLine($"     timing: a message on an attached thread {attached:F2} µs; attach + message + detach {perCall:F2} µs");

        tc.ReleaseGlobal(kept); tc.ReleaseGlobal(account); tc.ReleaseGlobal(routine); tc.ReleaseGlobal(loop);
        inst.Terminate();
        Console.WriteLine(failures == 0 ? "hostapi: all ok" : $"hostapi: {failures} FAILED");
        return failures == 0 ? 0 : 1;
    }
}
